services:
  api:
    build: .
    container_name: recharge-plataform-api
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      # - /app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://docker:docker@db:5432/recharge

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: recharge
    ports:
      - "5432:5432"
