version: '3.8'

services:
  api:
    build: .
    container_name: nestjs-api
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development