[build]
builder = "nixpacks"

[deploy]
startCommand = "npx prisma migrate deploy && npm run start:railway"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
