[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:railway"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.hooks]
postdeploy = "npm run prisma:seed"
